{% set name = "inplace-abn" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inplace-abn-{{ version }}.tar.gz
  sha256: 7c286ca53d35cb37b0d1f8b9beb5a910c694129d3d4f7b8e53188370bb260c27

build:
  number: 0
  skip: true  # [osx]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - pytorch >=2.4.0
    - setuptools
    - setuptools_scm
  run:
    - python

test:
  imports:
    - inplace_abn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mapillary/inplace_abn
  summary: In-Place Activated BatchNorm for Memory-Optimized Training of DNNs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
